In [1]:
# Arithmatic OPERATION

In [24]:
#1D ARRAY IN ARITHMATIC OPERATION

In [11]:
import numpy as np

var = np.array([1,2,3,4,5])

varadd = var + 3

print(varadd) 

[4 5 6 7 8]


In [12]:
import numpy as np

var = np.array([1,2,3,4,5])

varadd = var - 3

print(varadd) 

[-2 -1  0  1  2]


In [13]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])

varadd = var1 * 3

print(varadd) 

[ 3  6  9 12 15]


In [18]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])

varadd = var1 + var2

print(varadd) 

[ 2  4  6  8 10]


In [21]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])

varadd = np.add(var1,var2)

print(varadd) 

[ 2  4  6  8 10]


In [22]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([1,2,3,4,5])

varadd = np.add(var1,3)

print(varadd) 

[4 5 6 7 8]


In [15]:
var = np.array([1,2,3,4,5])

varadd = var * 3

print(varadd) 

[ 3  6  9 12 15]


In [16]:
var = np.array([1,2,3,4,5])

varadd = var / 3

print(varadd) 

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [17]:
var = np.array([1,2,3,4,5])

varadd = var % 3

print(varadd) 

[1 2 0 1 2]


In [28]:
var = np.array([1,2,3,4,5])

varadd = np.reciprocal(var) 

print(varadd) 

[1 0 0 0 0]


In [23]:
#2D ARRAY ARITHMATIC OPERATION

In [26]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21 + var22

print(varadd) 

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [27]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21 * var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [29]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd = var21 - var22

print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[0 0 0 0]
 [0 0 0 0]]
