In [17]:
#Shuffle Function

In [5]:
import numpy as np
A =np.array([1,2,3,4,5])
np.random.shuffle(A)
print(A)

[1 5 3 2 4]


In [16]:
#UNIQUE Function

In [11]:
B = np.array([1,2,3,4,2,3,5,6,4,7])
C = np.unique(B)
print(C)

[1 2 3 4 5 6 7]


In [14]:
B1 = np.array([1,2,3,4,2,3,5,6,4,7])
C1 = np.unique(B1,return_index = True)
print(C1)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 6, 7, 9], dtype=int64))


In [13]:
B2 = np.array([1,2,3,4,2,3,5,6,4,7])
C2 = np.unique(B2,return_index = True,return_counts=  True)
print(C2)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 6, 7, 9], dtype=int64), array([1, 2, 2, 2, 1, 1, 1], dtype=int64))


In [18]:
#RESIZE Fubction

In [20]:
var = np.array([1,2,3,4,5,6])
Y = np.resize(var,(2,3))
print(Y)

[[1 2 3]
 [4 5 6]]


In [21]:
var = np.array([1,2,3,4,5,6])
Y = np.resize(var,(3,2))
print(Y)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
#FLATTEN FUNCTION

In [27]:
var1 = np.array([1,2,3,4,5,6])
Y1 = np.resize(var1,(3,2))
print(Y1)
print()
print(Y.flatten(order='C'))  # c is default

[[1 2]
 [3 4]
 [5 6]]

[1 3 5 2 4 6]


In [37]:
var1 = np.array([1,2,3,4,5,6])
Y1 = np.resize(var1,(3,2))
print(Y1)
print()
print('Flatten :',Y.flatten(order='F')) #F &c to is random change of row
print('Ravel : ',np.ravel(Y1,order= 'A')) #A & K to change column of the order 

[[1 2]
 [3 4]
 [5 6]]

Flatten : [1 3 5 2 4 6]
Ravel :  [1 2 3 4 5 6]
