#DATA TYPES

In [3]:
import numpy as np
arr= np.array([1,2,3,4,5,12,24,32])
print("Data type :", arr.dtype)

Data type : int32


In [4]:
arr= np.array([0.1,20.22,35.51,4.5])
print("Data type :", arr.dtype)

Data type : float64


In [5]:
arr= np.array(["A","B","C","D"])
print("Data type :", arr.dtype)

Data type : <U1


In [6]:
arr= np.array(["A","B","C","D",1,2,3,4])
print("Data type :", arr.dtype)

Data type : <U11


In [12]:
x = np.array([1,2,3,4,5])
print("Data type :", x.dtype)

Data type : int32


In [13]:
x = np.array([1,2,3,4,5], dtype = np.int8)
print("Data type :", x.dtype)
print(x)

Data type : int8
[1 2 3 4 5]


In [18]:
x = np.array([1,2,3,4,5], dtype = "f")
print("Data type :", x.dtype)
print(x)

Data type : float32
[1. 2. 3. 4. 5.]


In [19]:
x2 = np.array([1,2,3,4,5])

new = np.float32(x2)

print("Data type :", x2.dtype)
print("Data type :", new.dtype)

print(x2)
print(new)

Data type : int32
Data type : float32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [20]:
x2 = np.array([1,2,3,4,5])

new = np.float32(x2)

new_1 = np.int_(new)

print("Data type :", x2.dtype)
print("Data type :", new.dtype)
print("Data type :", new_1.dtype)

print(x2)
print(new)
print(new_1)

Data type : int32
Data type : float32
Data type : int32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [21]:
x3 = np.array([1,2,3,4,5])

new_1 = x2.astype(float)

print(x3)
print(new_1)


[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [23]:
x5 = np.array([1.2,2.4,3.2,4.1])

new_2 = x5.astype(int)

print(x5)
print(new_2)

[1.2 2.4 3.2 4.1]
[1 2 3 4]
