In [8]:
import numpy as np

var = np.array([9,8,7,6])

print(var[3])
print(var[-2])

6
7


In [20]:
var1 = np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.ndim)
print()
print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2

7


In [29]:
var2 = np.array([[[1,2,3],[6,7,8]]])
print(var2)
print(var2.ndim)
print()
print(var2[0,1,2])

[[[1 2 3]
  [6 7 8]]]
3

8


In [30]:
#SLICING

In [44]:
var4 = np.array([9,8,7,6,5,4,3])
#                0,1,2,3,4,5,6
print(var4)
print(var4.ndim)
print()
print("2 to 5 :", var4[1:5])
print("2 to end : ",var4[1:])
print("Start to 5 :" , var[:5])
print(["Stop :", var4 [1:6:2]])

[9 8 7 6 5 4 3]
1

2 to 5 : [8 7 6 5]
2 to end :  [8 7 6 5 4 3]
Start to 5 : [9 8 7 6]
['Stop :', array([8, 6, 4])]


In [47]:
x = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(x)
print()
print("8 to 5 :", x[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5 : [12 13 14 15]
