In [1]:
import numpy as np

In [7]:
x = np.array([9,8,7,6,5,4])
print(x) 
print()
for i in x:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [10]:
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
for m in var:
    print(m)
print()
for k in var:
    for l in k:
        print(l)
   

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [16]:
var1 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var1)
print(var1.ndim)
print()
for i in var1:
    for j in i:
        for k in j:
            print(k)

[[[9 8 7 6]
  [1 2 3 4]]]
3

9
8
7
6
1
2
3
4


In [19]:
var2 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var2)
print(var2.ndim)
print()

for i in np.nditer(var2,flags=['buffered'],op_dtypes=['S']):
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]
3

b'9'
b'8'
b'7'
b'6'
b'1'
b'2'
b'3'
b'4'


In [21]:
var2 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var2)
print(var2.ndim)
print()

for i,d in np.ndenumerate(var2):
    print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
