In [1]:
#Join Array

In [3]:
import numpy as np
var  = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])
arr = np.concatenate((var,var1))
print(arr)

[1 2 3 4 9 8 7 6]


In [9]:
vr  = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])

arr_new = np.concatenate((vr,vr1),axis =0)

print(vr)
print()
print(vr1)
print()
print(arr_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [21]:
vr_1  = np.array([1,2,3,4])
vr_2 = np.array([9,8,7,6])

ar_new = np.stack((vr_1,vr_2),axis =0)
ar_new1 = np.hstack((vr_1,vr_2)) #row
ar_new2 = np.vstack((vr_1,vr_2)) #column
ar_new3 = np.dstack((vr_1,vr_2)) #hieght
print(ar_new)
print()
print(ar_new1)
print()
print(ar_new2)
print()
print(ar_new3)
print()

[[1 2 3 4]
 [9 8 7 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]

