# MATRIX FUNCTION IN NUMPY ARRAYS

In [2]:
# 1. TRANSPOSE
# 2. SWAPAXES
# 3. INVERSE
# 4. POWER
# 5. DETERMINATE

In [3]:
# 1. TRANSPOSE

In [4]:
import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)  # T is shortcut of using Transpose 

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [5]:
# 2. SWAPAXES

In [6]:
var_1 = np.matrix([[1,2,3],[4,5,6]])
print(var_1)
print()
print(np.swapaxes(var_1,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [7]:
var_2 = np.matrix([[1,2],[3,4]])
print(var_2)
print()
print(np.swapaxes(var_2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [8]:
# 3. INVERSE

In [9]:
var_3 = np.matrix([[1,2],[3,4]])
print(var_3)
print()
print(np.linalg.inv(var_3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
# 4. POWER

In [11]:
var_4 = np.matrix([[1,2],[3,4]])
print(var_4)
print()
print(np.linalg.matrix_power(var_4,2))
print()
print(np.linalg.matrix_power(var_4,0))
print()
print(np.linalg.matrix_power(var_4,-2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [12]:
# 5. DETERMINATE

In [13]:
var_5 = np.matrix([[1,2,3],[3,4,5],[1,2,3]])
print(var_5)
print()
print(np.linalg.det(var_5))

[[1 2 3]
 [3 4 5]
 [1 2 3]]

0.0
