In [1]:
# MATRAIX

In [2]:
import numpy as np

var = np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [3]:
var1 = np.array([[1,2,3],[1,2,3]])
var2 = np.array([[1,2,3],[1,2,3]])
print(var1)
print()
print(type(var1))
print()
print(var1 * var2)

[[1 2 3]
 [1 2 3]]

<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]


In [4]:
# Addition

In [5]:
var_1 = np.matrix([[1,2,3],[1,2,3]])
var_2 = np.matrix([[1,2,3],[1,2,3]])

print(var)
print(type(var))
print()
print(var_1 + var_2)

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[2 4 6]
 [2 4 6]]


In [6]:
# Substraction

In [7]:
var_3 = np.matrix([[1,2,3],[1,2,3]])
var_4 = np.matrix([[1,2,3],[1,2,3]])

print(var)
print(type(var))
print()
print(var_3 - var_4)

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[0 0 0]
 [0 0 0]]


In [8]:
# Multiplication

In [9]:
var_5 = np.matrix([[1,2],[1,2]])
var_6 = np.matrix([[1,2],[1,2]])

print(var)
print(type(var))
print()
print(var_5 * var_6)

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]


In [10]:
var_7 = np.matrix([[1,2],[1,2]])
var_8 = np.matrix([[1,2],[1,2]])

print(var)
print(type(var))
print()
print(var_7 * var_8)
print()
print(var_7.dot(var_8))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]
