# Welcome to Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[1,2,3,4]],np.int64)

In [3]:
myarr[0,1]

2

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 1, 45,  3,  4]], dtype=int64)

# Array Creation : Conversion from other python structures

In [8]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])


In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({32,34,23})

array({32, 34, 23}, dtype=object)

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
zeros.shape

(2, 5)

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,5,4)

In [21]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [22]:
emp = np.empty([4,6])

In [23]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511018e-306, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23037657e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
       [2.22522053e-306, 1.11261095e-306, 1.06809792e-306,
        1.11261095e-306, 1.42410974e-306, 2.56761491e-312]])

In [24]:
emp_like = np.empty_like([lspace])

In [25]:
emp_like

array([[1.        , 2.33333333, 3.66666667, 5.        ]])

In [26]:
ide = np.identity(45)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

In [29]:
arr = np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr = arr.reshape(3,33)

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.shape

(99,)