ZEROS

In [4]:
import numpy as np 
arr_zero = np.zeros(5)
arr_zero1 = np.zeros((3,4))
print(arr_zero)
print()
print(arr_zero1)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ONE'S

In [7]:
 arr_one = np.ones(4)
arr_one1= np.ones((4,3))
print(arr_one)
print()
print(arr_one1)

[1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#EMPTY

In [8]:
arr_em = np.empty(4)
print(arr_em)

[1. 1. 1. 1.]


In [ ]:
#RANGE

In [10]:
arr_rn = np.arange(4)
print(arr_rn)

[0 1 2 3]


In [ ]:
 #DIAGONAL

In [11]:
arr_dia = np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
arr_dia = np.eye(3,5)
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
#LINSPACE

In [18]:
arr_lin = np.linspace(0,20,num =5)
print(arr_lin)


[ 0.  5. 10. 15. 20.]
