In [12]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [11]:
l = []
for i in range (1,5):
    int_1 = int(input("enter:"))
    l.append(int_1)

print(np.array(l))

enter: 12
enter: 1
enter: 13
enter: 14


[12  1 13 14]


In [14]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
print(arr)
print(arr.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [15]:
arr3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [17]:
arr = np.array([1,2,3,4], ndmin = 20)
print(arr)
print(arr.ndim)

[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]
20
