In [ ]:
#RANDOM

In [ ]:
#Rand()

In [5]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.29529645 0.73584303 0.87176061 0.04366705]


In [7]:
var1 = np.random.rand(3,2)
print(var1)

[[0.80492764 0.51703277]
 [0.97149002 0.43730268]
 [0.90188303 0.73040004]]


In [ ]:
#RANDN()

In [8]:
var2 = np.random.randn(5)
print(var2)

[-0.91141244 -1.58434519  1.96379147 -0.29532216 -0.85745045]


In [ ]:
#RANF()

In [9]:
var3 = np.random.ranf(4)
print(var3)

[0.4006638  0.6254319  0.26204023 0.49328091]


In [ ]:
#RANDINT()

In [11]:
var4 = np.random.randint(5,20,5)
print(var4)

[17 10  5  9 11]
