In [2]:
#SEARCH

In [8]:
import numpy as np
var = np.array([1,2,3,4,2,5,2,5,6,7,3])
#               0,1,2,3,4,5,6,7,8,9,10
x = np.where((var % 2) == 0)
print(x)

(array([1, 3, 4, 6, 8], dtype=int64),)


In [9]:
#Seach Sorted Array

In [16]:
var_1 = np.array([1,2,3,4,9,10])
#                 0,1,2,3,4,5,6,
x1 = np.searchsorted(var_1 , [5,6,7],side='right') 
print(x1)

[4 4 4]


In [17]:
#SORT ARRAY

In [24]:
var_2 = np.array([4,3,2,1,12,5,22,45,16,65,21])
#                 0,1,2,3,4,5,6,7,8,9,10
print(np.sort(var_2))


[ 1  2  3  4  5 12 16 21 22 45 65]


In [25]:
var_2 = np.array([[4,3,2],[1,12,5],[22,45,16]])
#                 0,1,2,3,4,5,6,7,8,9,10
print(np.sort(var_2))

[[ 2  3  4]
 [ 1  5 12]
 [16 22 45]]


In [22]:
var_3 = np.array(['m','a','n','a','s','i'])
#                 0,1,2,3,4,5,6,7,8,9,10
print(np.sort(var_3))

['a' 'a' 'i' 'm' 'n' 's']


In [26]:
#FILTER ARRAY

In [35]:
x = np.array(['m','a','n','u'])

m = [True,False,False,True]
new_a = x[m]

print(new_a)
print(type(new_a))

['m' 'u']
<class 'numpy.ndarray'>
